### PR TITLE
Add examples for ImmutableReducerStores

### PR DESCRIPTION
**Pull request by AlanFoster**
image

### CODE REVIEW

**Comment by mako-taco** [comment]
Just gotta change that title to include the word 'Reducer'

**Comment by AlanFoster** [comment]
@mako-taco Fixed :+1:

**Comment by AlanFoster** [comment]
@mako-taco / @jhorwit2 Do we need to do anything extra to get http://fluxthis.io updated with the latest docs?

**Comment by jhorwit2** [comment]
@AlanFoster it's live: https://fluxthis.io/#/docs/immutable-reducer-stores

**Comment by AlanFoster** [comment]
@jhorwit2 Great, thanks very much :+1:

**Pull request merged**
